[uWSGI] getting INI configuration from config.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3684]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.14 (64bit) on [Fri Apr 13 17:28:08 2018] ***
compiled with version: 5.4.0 20160609 on 17 March 2017 09:15:21
os: Linux-4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016
nodename: iZwz9cvfx14bag99mo2lbsZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/www/apps/nanhu
detected binary path: /home/www/python27forflask/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/apps/nanhu/
your processes number limit is 7859
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:19000 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Set PythonHome to /home/www/python27forflask
Python main interpreter initialized at 0xe82950
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166144 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
/home/www/python27forflask/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe82950 pid: 25638 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25638)
spawned uWSGI worker 1 (pid: 25641, cores: 2)
*** Stats server enabled on 127.0.0.1:19001 fd: 9 ***
[pid: 25641|app: 0|req: 1/1] 210.72.27.66 () {42 vars in 713 bytes} [Fri Apr 13 17:28:15 2018] GET / => generated 12314 bytes in 21 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 25641|app: 0|req: 3/2] 210.72.27.66 () {40 vars in 662 bytes} [Fri Apr 13 17:28:15 2018] GET /static/css/ibase.css => generated 814 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 277 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 3/3] 210.72.27.66 () {40 vars in 656 bytes} [Fri Apr 13 17:28:15 2018] GET /static/css/ol.css => generated 3554 bytes in 6 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 4/4] 210.72.27.66 () {40 vars in 643 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/jsons.js => generated 40787 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 5/5] 210.72.27.66 () {40 vars in 647 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/echarts.js => generated 2265667 bytes in 54 msecs via sendfile() (HTTP/1.1 200) 7 headers in 285 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 7/6] 210.72.27.66 () {40 vars in 643 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/ibase.js => generated 1748 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 279 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 7/7] 210.72.27.66 () {40 vars in 637 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/ol.js => generated 472648 bytes in 6 msecs via sendfile() (HTTP/1.1 200) 7 headers in 282 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 9/8] 210.72.27.66 () {40 vars in 653 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/statistics.js => generated 31629 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 281 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 9/9] 210.72.27.66 () {40 vars in 651 bytes} [Fri Apr 13 17:28:15 2018] GET /static/js/main/main.js => generated 54936 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 281 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 10/10] 210.72.27.66 () {40 vars in 695 bytes} [Fri Apr 13 17:28:15 2018] GET /static/images/check-no.png => generated 8721 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 265 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 11/11] 210.72.27.66 () {40 vars in 689 bytes} [Fri Apr 13 17:28:15 2018] GET /static/images/house.png => generated 4177 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 266 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 12/12] 210.72.27.66 () {40 vars in 687 bytes} [Fri Apr 13 17:28:15 2018] GET /static/images/fish.png => generated 5056 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 265 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 13/13] 210.72.27.66 () {40 vars in 687 bytes} [Fri Apr 13 17:28:15 2018] GET /static/images/open.png => generated 3048 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 266 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 14/14] 210.72.27.66 () {40 vars in 689 bytes} [Fri Apr 13 17:28:15 2018] GET /static/images/close.png => generated 1753 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 266 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 15/15] 210.72.27.66 () {44 vars in 690 bytes} [Fri Apr 13 17:28:44 2018] GET /static/js/ol.js => generated 472648 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 282 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 16/16] 210.72.27.66 () {48 vars in 853 bytes} [Fri Apr 13 17:29:06 2018] POST /api/modify => generated 7 bytes in 86 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[pid: 25641|app: 0|req: 17/17] 210.72.27.66 () {48 vars in 853 bytes} [Fri Apr 13 17:29:20 2018] POST /api/modify => generated 7 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 1)
[pid: 25641|app: 0|req: 18/18] 210.72.27.66 () {40 vars in 693 bytes} [Fri Apr 13 17:29:30 2018] GET /static/images/upload/null => generated 233 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 25641|app: 0|req: 19/19] 210.72.27.66 () {42 vars in 740 bytes} [Fri Apr 13 17:29:51 2018] GET /nanhu23d => generated 6534 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 1)
[pid: 25641|app: 0|req: 20/20] 210.72.27.66 () {40 vars in 694 bytes} [Fri Apr 13 17:33:52 2018] GET /mobile => generated 4300 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 25641|app: 0|req: 21/21] 210.72.27.66 () {42 vars in 777 bytes} [Fri Apr 13 17:37:24 2018] GET /mobile => generated 4300 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 1)
[pid: 25641|app: 0|req: 22/22] 210.72.27.66 () {42 vars in 756 bytes} [Fri Apr 13 17:37:24 2018] GET /static/css/ol.css => generated 3554 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 0)
[pid: 25641|app: 0|req: 23/23] 210.72.27.66 () {42 vars in 737 bytes} [Fri Apr 13 17:37:24 2018] GET /static/js/ol.js => generated 472648 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 282 bytes (0 switches on core 1)
[pid: 25641|app: 0|req: 24/24] 210.72.27.66 () {42 vars in 754 bytes} [Fri Apr 13 17:37:36 2018] GET /favicon.ico => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[2018-04-13 17:38:03,133] ERROR in app: Exception on /api/appcreatefeature [POST]
Traceback (most recent call last):
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/api/views.py", line 71, in createfeature
    file=open(path,'wb')
IOError: [Errno 2] No such file or directory: '/home/www/apps/nanhu/app\\static\\images\\upload/1523612283.jpg'
[pid: 25641|app: 0|req: 25/25] 210.72.27.66 () {36 vars in 557 bytes} [Fri Apr 13 17:38:03 2018] POST /api/appcreatefeature => generated 291 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[2018-04-13 17:39:31,838] ERROR in app: Exception on /api/appcreatefeature [POST]
Traceback (most recent call last):
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/api/views.py", line 71, in createfeature
    file=open(path,'wb')
IOError: [Errno 2] No such file or directory: '/home/www/apps/nanhu/app\\static\\images\\upload/1523612371.jpg'
[pid: 25641|app: 0|req: 26/26] 210.72.27.66 () {36 vars in 557 bytes} [Fri Apr 13 17:39:31 2018] POST /api/appcreatefeature => generated 291 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
[pid: 25641|app: 0|req: 27/27] 210.72.27.66 () {42 vars in 777 bytes} [Fri Apr 13 17:42:01 2018] GET /mobile => generated 4300 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 25641|app: 0|req: 28/28] 210.72.27.66 () {42 vars in 754 bytes} [Fri Apr 13 17:42:02 2018] GET /favicon.ico => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 1)
[2018-04-13 17:42:48,153] ERROR in app: Exception on /api/appcreatefeature [POST]
Traceback (most recent call last):
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/www/python27forflask/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/api/views.py", line 71, in createfeature
    file=open(path,'wb')
IOError: [Errno 2] No such file or directory: '/home/www/apps/nanhu/app\\static\\images\\upload/1523612568.jpg'
[pid: 25641|app: 0|req: 29/29] 210.72.27.66 () {36 vars in 557 bytes} [Fri Apr 13 17:42:48 2018] POST /api/appcreatefeature => generated 291 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
